#!/bin/bash

set -u

set +e
jsFiles=($(git diff --cached --name-only --diff-filter=ACMR | grep -Ee '\.tsx{0,1}$'))
set -e

existingJsFiles=()
for file in "${jsFiles[@]}"; do
  if [ -f "$file" ]; then
    existingJsFiles+=("$file")
  fi
done

if [ "${#existingJsFiles[@]}" -ne 0 ]; then
  npx eslint --fix -- "${existingJsFiles[@]}"
  npx prettier --write -- "${existingJsFiles[@]}"
fi
